### ISSUE TITLE
Alternate way of creating footnotes and footers?

### ISSUE THREAD

**Issue by kizu** [shower/jekyller#2]
Is there any such way?

I'd say that using `<hr/>` could fit it, but it would conflict with headerless slides.

So, we could think on which custom markup to use for such purpose.

And/or this could apply to footers also.

**Comment by kizu** [comment]
`<hr/>` is taken by headerless slides. So, we need to find out the best syntax for this.

**Comment by pepelsbey** [comment]
Footer on Shower slides is hidden note for speaker, so why not `// Lorem ipsum dolor sit amet`?

**Comment by kizu** [comment]
@pepelsbey ok, done. Moved `.note` thingie to separate #17.
