### ISSUE TITLE
/shower /pictures and /themes folder are not copied

### ISSUE THREAD

**Issue by tpoisot** [shower/jekyller#24]
Using the new version of jekyll, none of the important folders are copied in the _site directory, which means they have to be copied by hand each time the slides are generated.

**Comment by kizu** [comment]
Which version of Jekyll do you have exactly? I just tried Jekyller with `jekyll 1.0.3` and everything works ok, it also works ok at GitHub Pages now.

**Comment by tpoisot** [comment]
Weird. I'm using `jekyll 1.0.2` in Fedora 19 (`ruby 2.0.0p195`). 

If that helps, I run things with `jekyll serve -w`.

**Comment by clkao** [comment]
apparently this is caused by _config.yml having:

```
exclude: [shower,themes]
```

**Comment by kizu** [comment]
Those lines was removed from the config recently. Thanks for mentioning this issue!
