### ISSUE TITLE
Deprecated Jekyll integration

### ISSUE THREAD

**Issue by PovilasID** [shower/jekyller#26]
It seams that Jekyll is no longer supporting functions Jekller needs or doing it in different manner. I think that because of warning I get after trying to run `jekyll build` I am additional information apart form build folder which looks like this: 

```
←[33m       Deprecation: Auto-regeneration can no longer be set from your config
uration file(s). Use the --watch/-w command-line option instead.←[0m
←[33m       Deprecation: The 'server' configuration option is no longer accepted
. Use the 'jekyll serve' subcommand to serve your site with WEBrick.←[0m
```

It does not seams to stop it from building jet if I try to alter some setting in config file I get punished by bunch of ugly errors in my console and no css implementation in final build. 

```
 ___________________________________________________________________________
| Maruku tells you:
+---------------------------------------------------------------------------
| Could not find ref_id = "md_entitylsquo_xcax83xc9x99uxc9x99" for md_link([md_
ntity("lsquo"), "\xCA\x83\xC9\x99u\xC9\x99"],"md_entitylsquo_xcax83xc9x99uxc9x9
")
| Available refs are []
```

This is the manin part of errors I get.

**Comment by kizu** [comment]
Was fixed in #27
