### ISSUE TITLE
Duplicate /themes and /shower/themes

### ISSUE THREAD

**Issue by dm4** [shower/jekyller#28]
After doing `git clone --recursive git://github.com/shower/jekyller.git`, there are duplicate folders `/themes` and `/shower/themes`.

Should we remove the `/themes` and keep `/shower/themes`?

Thanks!

**Comment by kizu** [comment]
Sadly, we can't do this: GitHub Pages clone submodules non-recursively (at least this was this way when I checked the last time), so we can't use `/shower/themes` from `shower`.
